### PR TITLE
Update apt packages to include nano

### PR DESCRIPTION
**Pull request by RobinL**
Users have been asking for nano so they don't get stuck in vim

### CODE REVIEW

**Comment by RobinL** [comment]
If we were feeling nice we'd also make sure nano is set as default in everyone's gitconfig but I don't recommend we do this because (as far as I know), it's not that simple (we don't want to mess about with editing everyone's config files, which they may already have set up how they like.

Would it maybe be easier to set global default text editor (i.e. not just git) to nano?

**Comment by RobinL** [comment]
I added `RUN update-alternatives --set editor /bin/nano` which seems to successfully make git default to nano

**Comment by davidread** [comment]
It didn't work for me until I unset my EDITOR env variable. I don't know what set it - it's not in the our Docker file or the rocker Dockerfile, or start.sh. I assume it gets set somewhere along the way and so I've added the `unset EDITOR`.

**Comment by davidread** [comment]
Confirmed that others have EDITOR set to vi by default, so it needs unsetting.

**Comment by davidread** [comment]
This got released on rstudio 3.4.2-6. See: https://github.com/ministryofjustice/analytics-platform-rstudio/releases

**Pull request merged**
