### PR TITLE
Remove/nodejs

### PR DESCRIPTION
**Pull request by damacus**

### CODE REVIEW

**Comment by xoen** [comment]
(approved as it makes sense to remove NodeJS from RStudio in principle although I can't be personally 100% sure it's actually not used)

**Comment by damacus** [comment]
@davidread said there were some projects using it. But they're no longer actively used.

**Comment by xoen** [comment]
Oh, weird. Nice one then, I imagine it would shave some bits off the docker image which always helps ⭐ 

(I wonder if in general we should have more comments in the `Dockerfile`s to say why something was added. So that if something similar happens, the future us have some clues/hints of why something is there and whether it's then safe to remove)

**Comment by RobinL** [comment]
@damacus 

I missed this but another user just brought it to my attention. 

IIRC this was added so that plots using vega-lite render correctly in R Markdown reports that are outputting to .png.

This functionality is  reasonably important.  It's possible that it now works without nodejs needing to be installed.

I think this is an example of where it should work:
https://github.com/moj-analytical-services/platform_demos/blob/master/demos_of_functionality/04_reticulate_rmarkdown.Rmd

**Comment by damacus** [comment]
@RobinL I'm keen to know if this is actively being used still. Needing to Install, R, Python and NodeJS in an image feels very OTT

**Comment by Rich3185** [comment]
Hi chaps! I am _planning_ to use Vega charts in RShiny, but realistically I am months away. 

As Robin points out I don't know if it still needs NodeJS. 

If I'm the only person needing it, maybe there is a more elegant way of providing what I need further down the road. Vega seemed to be the only way of putting mouse-over charts in a Shiny app that looked professional a year ago. 

Might be worth a shout-out on #analytical-platform.

**Comment by RobinL** [comment]
Things definitely needed:
- Python. Because it's common for people to use reticulate, e.g. for access Athena

Things I'm not sure about:
- I think it's fairly likely vega works for html charts without nodejs installed
- I think there's a reasonable chance it might even work for png/imaeg outputs without node js

Can I roll the latest version of R Studio with node JS removed  to myself using the control panel or do I need someone to do it for me?  Happy to do a few tests.



FWIW here's something else that can be deleted because we no longer use the ODBC drivers, instead we use the dbtools lib:

```
# Install SimbaAthena & configure ODBC drivers
RUN wget -q https://s3.amazonaws.com/athena-downloads/drivers/ODBC/SimbaAthenaODBC_1.0.3/Linux/simbaathena-1.0.3.1004-1.x86_64.rpm -P /tmp \
    && alien -i /tmp/simbaathena-1.0.3.1004-1.x86_64.rpm \
    && rm -f /tmp/simbaathena-1.0.3.1004-1.x86_64.rpm
COPY files/odbc* /etc/

```

**Comment by damacus** [comment]
SimaAthena deleted in #72

**Comment by damacus** [comment]
@RobinL We don't yet have a the new version of RStudio rolled out on the platform. We're looking at a beta rollout plan soon-ish.

**Pull request merged**
